/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class EditingConstants {
  public static readonly DEFAULT_WIDTH_VP = 320;
  public static readonly DEFAULT_SLIDER_VALUE = 50;
  public static readonly SLIDER_ROW_HEIGHT = 56;
  public static readonly PADDING_SLIDER_SM = 60;
  public static readonly PADDING_SLIDER_MD = 72;
  public static readonly LIST_SPACE = 4;
  public static readonly FILTER_ITEM_SIZE = 68;
  public static readonly FILTER_LIST_HEIGHT_HORIZONTAL = 96;
  public static readonly FILTER_LIST_WIDTH_VERTICAL = 96;
  public static readonly PADDING_VERTICAL_TOP_BOTTOM = 36;
  public static readonly HORIZONTAL_LAYOUT_WIDTH = 152;
  public static readonly FONT_SIZE_FILTER_NAME = 12;
  public static readonly LINE_HEIGHT_FILTER_NAME = 16;
  public static readonly MARGIN_FILTER_NAME = 6;
  public static readonly BORDER_RADIUS_FILTER_ITEM = 8;
  public static readonly BORDER_WIDTH_SELECTED = 2;
  public static readonly FONT_SIZE_COMPARE_BUTTON = 16;
  public static readonly LINE_HEIGHT_COMPARE_BUTTON = 22;
  public static readonly HEIGHT_COMPARE_BUTTON = 28;
  public static readonly BORDER_RADIUS_COMPARE_BUTTON = 14;
  public static readonly MARGIN_TOP_COMPARE_BUTTON = 12;

  public static readonly ASPECT_RATIO_PICTURE = 1.33;
  public static readonly FADING_EDGE_LENGTH = 80;
  public static readonly TITLE_FONT_WEIGHT = 700;
}