/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class BrowsingConstants {
  public static readonly DEFAULT_WIDTH_VP = 320;

  public static readonly GRID_COLUMNS_SM = 3;
  public static readonly GRID_COLUMNS_MD = 4;
  public static readonly GRID_COLUMNS_LG = 6;
  public static readonly GRID_COLUMNS_XL = 6;
  public static readonly GRID_COLUMNS_PINCH_SM = 4;
  public static readonly GRID_COLUMNS_PINCH_MD = 5;
  public static readonly GRID_COLUMNS_PINCH_LG = 8;
  public static readonly GRID_COLUMNS_PINCH_XL = 8;

  public static readonly GRID_GAP = 2;

  public static readonly TIME_FILTER_WIDTH = 216;
  public static readonly TIME_FILTER_HEIGHT = 40;
  public static readonly TIME_FILTER_BORDER_RADIUS = 32;
  public static readonly TIME_FILTER_PADDING = 2;
  public static readonly TIME_FILTER_ITEM_BORDER_RADIUS = 28;
  public static readonly TIME_FILTER_FONT_SIZE = 14;
  public static readonly TIME_FILTER_LINE_HEIGHT = 19;
  public static readonly DEFAULT_TIME_FILTER_INDEX = 2;

  public static readonly ALBUM_LIST_FONT_SIZE_SECONDARY = 14;
  public static readonly ALBUM_LIST_LINE_HEIGHT_SECONDARY = 19;
  public static readonly ALBUM_LIST_FONT_SIZE_TITLE = 24;
  public static readonly ALBUM_LIST_ITEM_HEIGHT = 56;
  public static readonly ALBUM_LIST_ICON_SIZE = 24;
  public static readonly ALBUM_LIST_ITEM_PADDING_HORIZONTAL = 16;
  public static readonly ALBUM_LIST_ITEM_MARGIN_BOTTOM = 8;
  public static readonly ALBUM_LIST_ITEM_MARGIN_LEFT = 8;
  public static readonly ALBUM_LIST_ITEM_MARGIN_LEFT_LARGE = 48;
  public static readonly ALBUM_LIST_ITEM_BORDER_RADIUS = 16;
  public static readonly ALBUM_LIST_ITEM_INNER_PADDING = 8;
  public static readonly ALBUM_LIST_CHECK_ICON_SIZE = 40;
  public static readonly ALBUM_LIST_CHECK_ICON_STROKE_WIDTH = 0.5;
  public static readonly ALBUM_LIST_SELECTED_ITEM_PADDING = 4;
  public static readonly ALBUM_LIST_SELECTED_ITEM_BORDER_RADIUS = 20;
  public static readonly ALBUM_LIST_BOTTOM_MARGIN = 28;
  public static readonly ALBUM_LIST_FONT_SIZE_DATE = 16;
  public static readonly ALBUM_LIST_DATE_MARGIN_LEFT = 16;

  public static readonly GESTURE_FINGERS = 2;
  public static readonly ANIMATION_DURATION = 500;
  public static readonly ASPECT_RATIO_PICTURE = 1.33;
  public static readonly FADING_EDGE_LENGTH = 80;
  public static readonly MOCK_PICTURE_COUNT = 64;

  public static readonly TITLE_BAR_MARGIN_TOP = 64;
  public static readonly TITLE_BAR_FONT_WEIGHT = 700;
}