/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  public static readonly SCREEN_RATIO_DEFAULT = 1.5;
  public static readonly SCREEN_RATIO_THRESHOLD = 1.2;
  public static readonly SCREEN_RATIO_THRESHOLD_LOW = 0.8;
  public static readonly BREAKPOINT_WIDTH_SMALL = 320;
  public static readonly BREAKPOINT_WIDTH_MEDIUM = 600;
  public static readonly BREAKPOINT_WIDTH_LARGE = 840;
  public static readonly BREAKPOINT_WIDTH_XL = 1440;

  public static readonly TAB_BAR_HEIGHT_BASE = 52;
  public static readonly TAB_BAR_EXTRA_PADDING = 26;

  public static readonly TITLE_BAR_HEIGHT = 56;

  public static readonly ICON_SIZE_DEFAULT = 24;

  public static readonly BUTTON_SIZE = 40;
  public static readonly BORDER_RADIUS_BUTTON = 20;

  public static readonly FONT_SIZE_TAB_TEXT = 10;
  public static readonly LINE_HEIGHT_TAB_TEXT = 13;
  public static readonly MARGIN_TOP_TAB_TEXT = 4;

  public static readonly FONT_SIZE_TITLE = 20;
  public static readonly LINE_HEIGHT_TITLE = 27;

  public static readonly FONT_SIZE_APP_NAME = 16;
  public static readonly LINE_HEIGHT_APP_NAME = 21;

  public static readonly FONT_SIZE_MAIN_TITLE = 26;
  public static readonly LINE_HEIGHT_MAIN_TITLE = 35;

  public static readonly BORDER_RADIUS_TAB_ITEM = 16;

  public static readonly WINDOW_DECOR_HEIGHT = 56;
  public static readonly DECOR_BUTTON_ICON_SIZE = 24;

  public static readonly PADDING_SM = 16;
  public static readonly PADDING_MD = 24;
  public static readonly PADDING_LG = 32;
  public static readonly PADDING_XL = 32;
  public static readonly MARGIN_HDS_TABS = 64;

  public static readonly SIDEBAR_ICON_EXTRA_WIDTH = 48;

  public static readonly MARGIN_LEFT_BUTTON = 8;

  public static readonly SCREEN_WIDTH_LARGE = 840;

  public static readonly WINDOW_UTIL_KEY = 'MultiPictureWindowUtil';

  public static readonly BREAKPOINTS_SM_NAME = 'sm';
  public static readonly BREAKPOINTS_MD_NAME = 'md';
  public static readonly BREAKPOINTS_LG_NAME = 'lg';
  public static readonly BREAKPOINTS_XL_NAME = 'xl';
  public static readonly BREAKPOINTS_INITIALIZE_NAME = 'md';
  public static readonly BREAKPOINT_ID_INITIALIZE_NAME = 'unknown';
}