/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class DefaultConstants {
  public static readonly DOMAIN = 0x0000;
  public static readonly LOG_TAG_DEFAULT_ABILITY = 'DefaultAbility';
  public static readonly DEFAULT_NAV_HEIGHT = 0;
  public static readonly BAR_WIDTH_HDS = 236;
  public static readonly BAR_SIDE_MARGIN_HDS = 84;

  public static readonly SIDEBAR_BUTTON_SIZE = 40;
  public static readonly SIDEBAR_BUTTON_FONT_SIZE = 24;
  public static readonly SIDEBAR_BUTTON_BORDER_RADIUS = 28;
  public static readonly SIDEBAR_BUTTON_POSITION_LEFT = 16;
  public static readonly SIDEBAR_BUTTON_POSITION_TOP = 8;
  public static readonly SIDEBAR_NAV_BAR_WIDTH = 240;
  public static readonly SIDEBAR_MARGIN_TOP_EXTRA = 64;
  public static readonly BREAKPOINT_THRESHOLD_WIDTH = 600;
  public static readonly SCREEN_RATIO_THRESHOLD_INDEX = 1.2;
}